name: Build Frontend Assets
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies
        run: npm install
      
      - name: Build with Vite
        env:
          VITE_SERVER_URL: ${{ secrets.SERVER_URL || 'http://localhost:5555' }}
          VITE_APP_TITLE: "ServerStatus-Nezha"
        run: npm run build
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
